### ISSUE TITLE
[Metadata] Tank metadata information

### ISSUE THREAD

**Issue by garsia0** [WickedPeanuts/OpenBound#1]
static TankInfo()
		{
			TankInfo tankInfo = new TankInfo("Armor Mobile")
			{
				Armor = ArmorType.Mech,
				Health = 1000,
				DelayBase = 525,
				DelayOffset = 10,
				ShotType = ShotType.Explosive,
				ShotStart = new Point(46, 30),
				ShotSpeed = 46,
				ShotWeight = 98
			};
			tankInfo.Shots[0].Delay = 250;
			tankInfo.Shots[0].Damage = 135;
			tankInfo.Shots[0].Scale = 100;
			tankInfo.Shots[0].FlameScale = 20;
			tankInfo.Shots[0].Splash = new Point(0, 0);
			tankInfo.Shots[0].Radius = new Point(68, 144);
			tankInfo.Shots[0].SetAngle(55, 10);
			tankInfo.Shots[0].SetFocus(40, 25);
			tankInfo.Shots[1].Delay = 470;
			tankInfo.Shots[1].Damage = 112;
			tankInfo.Shots[1].Scale = 120;
			tankInfo.Shots[1].FlameScale = 20;
			tankInfo.Shots[1].Splash = new Point(0, 0);
			tankInfo.Shots[1].Radius = new Point(56, 134);
			tankInfo.Shots[1].SetAngle(50, 15);
			tankInfo.Shots[1].SetFocus(38, 27);
			tankInfo.Shots[2].Delay = 800;
			tankInfo.Shots[2].Damage = 337;
			tankInfo.Shots[2].Scale = 60;
			tankInfo.Shots[2].FlameScale = 10;
			tankInfo.Shots[2].Splash = new Point(200, 120);
			tankInfo.Shots[2].Radius = new Point(70, 134);
			tankInfo.Shots[2].SetAngle(55, 10);
			tankInfo.Shots[2].SetFocus(55, 10);
			TankInfo tankInfo2 = new TankInfo("Mage")
			{
				Armor = ArmorType.Shield,
				Health = 760,
				Shield = 220,
				ShieldRegen = 30,
				DelayBase = 490,
				DelayOffset = 10,
				ShotType = ShotType.Laser,
				ShotStart = new Point(60, 36),
				ShotSpeed = 45,
				ShotWeight = 90
			};
			tankInfo2.Shots[0].Delay = 250;
			tankInfo2.Shots[0].Damage = 129;
			tankInfo2.Shots[0].Scale = 125;
			tankInfo2.Shots[0].Splash = new Point(0, 0);
			tankInfo2.Shots[0].Radius = new Point(66, 143);
			tankInfo2.Shots[0].SetAngle(50, 15);
			tankInfo2.Shots[0].SetFocus(50, 15);
			tankInfo2.Shots[1].Delay = 400;
			tankInfo2.Shots[1].Damage = 108;
			tankInfo2.Shots[1].Scale = 125;
			tankInfo2.Shots[1].Splash = new Point(0, 0);
			tankInfo2.Shots[1].Radius = new Point(54, 134);
			tankInfo2.Shots[1].SetAngle(50, 15);
			tankInfo2.Shots[1].SetFocus(50, 15);
			tankInfo2.Shots[2].Delay = 800;
			tankInfo2.Shots[2].Damage = 324;
			tankInfo2.Shots[2].Scale = 75;
			tankInfo2.Shots[2].Splash = new Point(150, 0);
			tankInfo2.Shots[2].Radius = new Point(60, 130);
			tankInfo2.Shots[2].SetAngle(50, 15);
			tankInfo2.Shots[2].SetFocus(50, 15);
			TankInfo tankInfo3 = new TankInfo("Nak Machine")
			{
				Armor = ArmorType.Mech,
				Health = 1100,
				DelayBase = 510,
				DelayOffset = 10,
				ShotType = ShotType.Contact,
				ShotStart = new Point(140, 33),
				ShotSpeed = 41,
				ShotWeight = 98
			};
			tankInfo3.Shots[0].Delay = 250;
			tankInfo3.Shots[0].Damage = 135;
			tankInfo3.Shots[0].Scale = 120;
			tankInfo3.Shots[0].Splash = new Point(0, 0);
			tankInfo3.Shots[0].Radius = new Point(60, 144);
			tankInfo3.Shots[0].SetAngle(170, 130);
			tankInfo3.Shots[0].SetFocus(170, 130);
			tankInfo3.Shots[1].Delay = 400;
			tankInfo3.Shots[1].Damage = 225;
			tankInfo3.Shots[1].Scale = 130;
			tankInfo3.Shots[1].Splash = new Point(0, 0);
			tankInfo3.Shots[1].Radius = new Point(70, 134);
			tankInfo3.Shots[1].SetAngle(170, 130);
			tankInfo3.Shots[1].SetFocus(170, 130);
			tankInfo3.Shots[2].Delay = 800;
			tankInfo3.Shots[2].Damage = 337;
			tankInfo3.Shots[2].Scale = 100;
			tankInfo3.Shots[2].Splash = new Point(0, 0);
			tankInfo3.Shots[2].Radius = new Point(70, 100);
			tankInfo3.Shots[2].SetAngle(170, 130);
			tankInfo3.Shots[2].SetFocus(170, 130);
			TankInfo tankInfo4 = new TankInfo("Trico")
			{
				Armor = ArmorType.Flesh,
				Health = 1100,
				DelayBase = 490,
				DelayOffset = 10,
				ShotType = ShotType.Explosive,
				ShotStart = new Point(60, 38),
				ShotSpeed = 43,
				ShotWeight = 98
			};
			tankInfo4.Shots[0].Delay = 250;
			tankInfo4.Shots[0].Damage = 135;
			tankInfo4.Shots[0].Scale = 100;
			tankInfo4.Shots[0].FlameScale = 10;
			tankInfo4.Shots[0].Splash = new Point(0, 0);
			tankInfo4.Shots[0].Radius = new Point(70, 144);
			tankInfo4.Shots[0].SetAngle(50, 10);
			tankInfo4.Shots[0].SetFocus(40, 20);
			tankInfo4.Shots[1].Delay = 400;
			tankInfo4.Shots[1].Damage = 75;
			tankInfo4.Shots[1].Scale = 135;
			tankInfo4.Shots[1].FlameScale = 10;
			tankInfo4.Shots[1].Splash = new Point(0, 0);
			tankInfo4.Shots[1].Radius = new Point(48, 134);
			tankInfo4.Shots[1].SetAngle(50, 10);
			tankInfo4.Shots[1].SetFocus(40, 20);
			tankInfo4.Shots[2].Delay = 800;
			tankInfo4.Shots[2].Damage = 337;
			tankInfo4.Shots[2].Scale = 50;
			tankInfo4.Shots[2].FlameScale = 10;
			tankInfo4.Shots[2].Splash = new Point(76, 0);
			tankInfo4.Shots[2].Radius = new Point(120, 120);
			tankInfo4.Shots[2].SetAngle(40, 20);
			tankInfo4.Shots[2].SetFocus(40, 20);
			TankInfo tankInfo5 = new TankInfo("Bigfoot")
			{
				Armor = ArmorType.Mech,
				Health = 1100,
				DelayBase = 520,
				DelayOffset = 10,
				ShotType = ShotType.Explosive,
				ShotStart = new Point(56, 42),
				ShotSpeed = 42,
				ShotWeight = 98
			};
			tankInfo5.Shots[0].Delay = 250;
			tankInfo5.Shots[0].Damage = 33;
			tankInfo5.Shots[0].Scale = 135;
			tankInfo5.Shots[0].FlameScale = 10;
			tankInfo5.Shots[0].Splash = new Point(0, 0);
			tankInfo5.Shots[0].Radius = new Point(55, 134);
			tankInfo5.Shots[0].SetAngle(40, 18);
			tankInfo5.Shots[0].SetFocus(35, 23);
			tankInfo5.Shots[1].Delay = 400;
			tankInfo5.Shots[1].Damage = 37;
			tankInfo5.Shots[1].Scale = 135;
			tankInfo5.Shots[1].FlameScale = 10;
			tankInfo5.Shots[1].Splash = new Point(0, 0);
			tankInfo5.Shots[1].Radius = new Point(42, 124);
			tankInfo5.Shots[1].SetAngle(40, 18);
			tankInfo5.Shots[1].SetFocus(35, 23);
			tankInfo5.Shots[2].Delay = 800;
			tankInfo5.Shots[2].Damage = 42;
			tankInfo5.Shots[2].Scale = 135;
			tankInfo5.Shots[2].FlameScale = 25;
			tankInfo5.Shots[2].Splash = new Point(0, 0);
			tankInfo5.Shots[2].Radius = new Point(48, 126);
			tankInfo5.Shots[2].SetAngle(35, 23);
			tankInfo5.Shots[2].SetFocus(35, 23);
			TankInfo tankInfo6 = new TankInfo("Boomer")
			{
				Armor = ArmorType.Flesh,
				Health = 1000,
				DelayBase = 480,
				DelayOffset = 10,
				ShotType = ShotType.Contact,
				ShotStart = new Point(75, 38),
				ShotSpeed = 35,
				ShotWeight = 98
			};
			tankInfo6.Shots[0].Delay = 250;
			tankInfo6.Shots[0].Damage = 156;
			tankInfo6.Shots[0].Scale = 100;
			tankInfo6.Shots[0].FlameScale = 20;
			tankInfo6.Shots[0].Splash = new Point(50, 0);
			tankInfo6.Shots[0].Radius = new Point(48, 124);
			tankInfo6.Shots[0].SetAngle(90, 10);
			tankInfo6.Shots[0].SetFocus(65, 35);
			tankInfo6.Shots[1].Delay = 400;
			tankInfo6.Shots[1].Damage = 65;
			tankInfo6.Shots[1].Scale = 100;
			tankInfo6.Shots[1].FlameScale = 20;
			tankInfo6.Shots[1].Splash = new Point(0, 0);
			tankInfo6.Shots[1].Radius = new Point(42, 114);
			tankInfo6.Shots[1].SetAngle(90, 10);
			tankInfo6.Shots[1].SetFocus(65, 35);
			tankInfo6.Shots[2].Delay = 800;
			tankInfo6.Shots[2].Damage = 391;
			tankInfo6.Shots[2].Scale = 65;
			tankInfo6.Shots[2].FlameScale = 10;
			tankInfo6.Shots[2].Splash = new Point(200, 120);
			tankInfo6.Shots[2].Radius = new Point(46, 120);
			tankInfo6.Shots[2].SetAngle(90, 10);
			tankInfo6.Shots[2].SetFocus(65, 35);
			TankInfo tankInfo7 = new TankInfo("Leon Launcher")
			{
				Armor = ArmorType.Mech,
				Health = 1050,
				DelayBase = 500,
				DelayOffset = 10,
				ShotType = ShotType.Laser,
				ShotStart = new Point(64, 34),
				ShotSpeed = 44,
				ShotWeight = 98
			};
			tankInfo7.Shots[0].Delay = 250;
			tankInfo7.Shots[0].Damage = 41;
			tankInfo7.Shots[0].Scale = 100;
			tankInfo7.Shots[0].FlameScale = 20;
			tankInfo7.Shots[0].Splash = new Point(0, 0);
			tankInfo7.Shots[0].Radius = new Point(54, 130);
			tankInfo7.Shots[0].SetAngle(50, 10);
			tankInfo7.Shots[0].SetFocus(50, 10);
			tankInfo7.Shots[1].Delay = 400;
			tankInfo7.Shots[1].Damage = 103;
			tankInfo7.Shots[1].Scale = 30;
			tankInfo7.Shots[1].Splash = new Point(90, 26);
			tankInfo7.Shots[1].Radius = new Point(42, 122);
			tankInfo7.Shots[1].SetAngle(50, 10);
			tankInfo7.Shots[1].SetFocus(50, 10);
			tankInfo7.Shots[2].Delay = 800;
			tankInfo7.Shots[2].Damage = 310;
			tankInfo7.Shots[2].Scale = 80;
			tankInfo7.Shots[2].Splash = new Point(90, 26);
			tankInfo7.Shots[2].Radius = new Point(42, 130);
			tankInfo7.Shots[2].SetAngle(50, 10);
			tankInfo7.Shots[2].SetFocus(50, 10);
			TankInfo tankInfo8 = new TankInfo("Lightning")
			{
				Armor = ArmorType.Shield,
				Health = 750,
				Shield = 300,
				ShieldRegen = 20,
				DelayBase = 500,
				DelayOffset = 10,
				ShotType = ShotType.Electric,
				ShotStart = new Point(60, 36),
				ShotSpeed = 47,
				ShotWeight = 90
			};
			tankInfo8.Shots[0].Delay = 250;
			tankInfo8.Shots[0].Damage = 129;
			tankInfo8.Shots[0].Scale = 75;
			tankInfo8.Shots[0].Splash = new Point(56, 20);
			tankInfo8.Shots[0].Radius = new Point(54, 134);
			tankInfo8.Shots[0].SetAngle(40, 18);
			tankInfo8.Shots[0].SetFocus(40, 18);
			tankInfo8.Shots[1].Delay = 300;
			tankInfo8.Shots[1].Damage = 216;
			tankInfo8.Shots[1].Scale = 75;
			tankInfo8.Shots[1].Splash = new Point(56, 20);
			tankInfo8.Shots[1].Radius = new Point(40, 143);
			tankInfo8.Shots[1].SetAngle(40, 18);
			tankInfo8.Shots[1].SetFocus(40, 18);
			tankInfo8.Shots[2].Delay = 800;
			tankInfo8.Shots[2].Damage = 324;
			tankInfo8.Shots[2].Scale = 90;
			tankInfo8.Shots[2].Splash = new Point(26, 20);
			tankInfo8.Shots[2].Radius = new Point(40, 143);
			tankInfo8.Shots[2].SetAngle(40, 18);
			tankInfo8.Shots[2].SetFocus(40, 18);
			TankInfo tankInfo9 = new TankInfo("J.D.")
			{
				Armor = ArmorType.Shield,
				Health = 700,
				Shield = 250,
				ShieldRegen = 20,
				DelayBase = 490,
				DelayOffset = 10,
				ShotType = ShotType.Electric,
				ShotStart = new Point(60, 40),
				ShotSpeed = 50,
				ShotWeight = 98
			};
			tankInfo9.Shots[0].Delay = 250;
			tankInfo9.Shots[0].Damage = 129;
			tankInfo9.Shots[0].Scale = 60;
			tankInfo9.Shots[0].Splash = new Point(45, 15);
			tankInfo9.Shots[0].Radius = new Point(64, 144);
			tankInfo9.Shots[0].SetAngle(45, 15);
			tankInfo9.Shots[0].SetFocus(45, 15);
			tankInfo9.Shots[1].Delay = 330;
			tankInfo9.Shots[1].Damage = 216;
			tankInfo9.Shots[1].Scale = 40;
			tankInfo9.Shots[1].Splash = new Point(60, 0);
			tankInfo9.Shots[1].Radius = new Point(52, 124);
			tankInfo9.Shots[1].SetAngle(45, 15);
			tankInfo9.Shots[1].SetFocus(45, 15);
			tankInfo9.Shots[2].Delay = 800;
			tankInfo9.Shots[2].Damage = 0;
			tankInfo9.Shots[2].Scale = 100;
			tankInfo9.Shots[2].Splash = new Point(68, 14);
			tankInfo9.Shots[2].Radius = new Point(30, 124);
			tankInfo9.Shots[2].SetAngle(45, 15);
			tankInfo9.Shots[2].SetFocus(45, 15);
			TankInfo tankInfo10 = new TankInfo("Asate")
			{
				Armor = ArmorType.Shield,
				Health = 750,
				Shield = 200,
				ShieldRegen = 30,
				DelayBase = 480,
				DelayOffset = 10,
				ShotType = ShotType.Laser,
				ShotStart = new Point(42, 35),
				ShotSpeed = 45,
				ShotWeight = 98
			};
			tankInfo10.Shots[0].Delay = 250;
			tankInfo10.Shots[0].Damage = 135;
			tankInfo10.Shots[0].Scale = 100;
			tankInfo10.Shots[0].Splash = new Point(0, 0);
			tankInfo10.Shots[0].Radius = new Point(54, 144);
			tankInfo10.Shots[0].SetAngle(60, 20);
			tankInfo10.Shots[0].SetFocus(60, 20);
			tankInfo10.Shots[1].Delay = 400;
			tankInfo10.Shots[1].Damage = 75;
			tankInfo10.Shots[1].Scale = 110;
			tankInfo10.Shots[1].Splash = new Point(0, 0);
			tankInfo10.Shots[1].Radius = new Point(46, 134);
			tankInfo10.Shots[1].SetAngle(60, 20);
			tankInfo10.Shots[1].SetFocus(60, 20);
			tankInfo10.Shots[2].Delay = 800;
			tankInfo10.Shots[2].Damage = 84;
			tankInfo10.Shots[2].Scale = 110;
			tankInfo10.Shots[2].Splash = new Point(0, 0);
			tankInfo10.Shots[2].Radius = new Point(44, 134);
			tankInfo10.Shots[2].SetAngle(55, 25);
			tankInfo10.Shots[2].SetFocus(55, 25);
			TankInfo tankInfo11 = new TankInfo("Ice")
			{
				Armor = ArmorType.Flesh,
				Health = 1200,
				DelayBase = 490,
				DelayOffset = 10,
				ShotType = ShotType.Contact,
				ShotStart = new Point(54, 50),
				ShotSpeed = 50,
				ShotWeight = 98
			};
			tankInfo11.Shots[0].Delay = 250;
			tankInfo11.Shots[0].Damage = 129;
			tankInfo11.Shots[0].Scale = 100;
			tankInfo11.Shots[0].Splash = new Point(0, 0);
			tankInfo11.Shots[0].Radius = new Point(66, 144);
			tankInfo11.Shots[0].SetAngle(70, 20);
			tankInfo11.Shots[0].SetFocus(60, 30);
			tankInfo11.Shots[1].Delay = 400;
			tankInfo11.Shots[1].Damage = 216;
			tankInfo11.Shots[1].Scale = 85;
			tankInfo11.Shots[1].Splash = new Point(0, 0);
			tankInfo11.Shots[1].Radius = new Point(56, 124);
			tankInfo11.Shots[1].SetAngle(70, 20);
			tankInfo11.Shots[1].SetFocus(60, 30);
			tankInfo11.Shots[2].Delay = 800;
			tankInfo11.Shots[2].Damage = 324;
			tankInfo11.Shots[2].Scale = 100;
			tankInfo11.Shots[2].Splash = new Point(130, 0);
			tankInfo11.Shots[2].Radius = new Point(60, 124);
			tankInfo11.Shots[2].SetAngle(60, 30);
			tankInfo11.Shots[2].SetFocus(60, 30);
			TankInfo tankInfo12 = new TankInfo("Turtle")
			{
				Armor = ArmorType.Flesh,
				Health = 960,
				DelayBase = 490,
				DelayOffset = 12,
				ShotType = ShotType.Contact,
				ShotStart = new Point(60, 30),
				ShotSpeed = 46,
				ShotWeight = 98
			};
			tankInfo12.Shots[0].Delay = 250;
			tankInfo12.Shots[0].Damage = 135;
			tankInfo12.Shots[0].Scale = 100;
			tankInfo12.Shots[0].Splash = new Point(0, 0);
			tankInfo12.Shots[0].Radius = new Point(56, 134);
			tankInfo12.Shots[0].SetAngle(50, 25);
			tankInfo12.Shots[0].SetFocus(50, 25);
			tankInfo12.Shots[1].Delay = 400;
			tankInfo12.Shots[1].Damage = 112;
			tankInfo12.Shots[1].Scale = 125;
			tankInfo12.Shots[1].Splash = new Point(0, 0);
			tankInfo12.Shots[1].Radius = new Point(46, 114);
			tankInfo12.Shots[1].SetAngle(50, 25);
			tankInfo12.Shots[1].SetFocus(50, 25);
			tankInfo12.Shots[2].Delay = 800;
			tankInfo12.Shots[2].Damage = 324;
			tankInfo12.Shots[2].Scale = 65;
			tankInfo12.Shots[2].Splash = new Point(70, 60);
			tankInfo12.Shots[2].Radius = new Point(46, 120);
			tankInfo12.Shots[2].SetAngle(50, 25);
			tankInfo12.Shots[2].SetFocus(50, 25);
			TankInfo tankInfo13 = new TankInfo("Grub")
			{
				Armor = ArmorType.Flesh,
				Health = 1000,
				DelayBase = 490,
				DelayOffset = 10,
				ShotType = ShotType.Electric,
				ShotStart = new Point(55, 38),
				ShotSpeed = 50,
				ShotWeight = 98
			};
			tankInfo13.Shots[0].Delay = 250;
			tankInfo13.Shots[0].Damage = 129;
			tankInfo13.Shots[0].Scale = 100;
			tankInfo13.Shots[0].Splash = new Point(0, 0);
			tankInfo13.Shots[0].Radius = new Point(50, 144);
			tankInfo13.Shots[0].SetAngle(60, 30);
			tankInfo13.Shots[0].SetFocus(55, 35);
			tankInfo13.Shots[1].Delay = 400;
			tankInfo13.Shots[1].Damage = 54;
			tankInfo13.Shots[1].Scale = 100;
			tankInfo13.Shots[1].Splash = new Point(0, 1800);
			tankInfo13.Shots[1].Radius = new Point(38, 120);
			tankInfo13.Shots[1].SetAngle(60, 30);
			tankInfo13.Shots[1].SetFocus(55, 35);
			tankInfo13.Shots[2].Delay = 800;
			tankInfo13.Shots[2].Damage = 5;
			tankInfo13.Shots[2].Scale = 100;
			tankInfo13.Shots[2].Splash = new Point(0, 1600);
			tankInfo13.Shots[2].Radius = new Point(36, 100);
			tankInfo13.Shots[2].SetAngle(60, 30);
			tankInfo13.Shots[2].SetFocus(60, 30);
			TankInfo tankInfo14 = new TankInfo("Dragon")
			{
				IsPrivate = true,
				Armor = ArmorType.Flesh,
				Health = 1000,
				Altitude = 30,
				DelayBase = 550,
				DelayOffset = 10,
				ShotType = ShotType.Explosive,
				ShotStart = new Point(54, 46),
				ShotSpeed = 50,
				ShotWeight = 90
			};
			tankInfo14.Shots[0].Delay = 250;
			tankInfo14.Shots[0].Damage = 156;
			tankInfo14.Shots[0].Scale = 125;
			tankInfo14.Shots[0].Splash = new Point(0, 0);
			tankInfo14.Shots[0].Radius = new Point(58, 136);
			tankInfo14.Shots[0].SetAngle(60, 30);
			tankInfo14.Shots[0].SetFocus(60, 30);
			tankInfo14.Shots[1].Delay = 400;
			tankInfo14.Shots[1].Damage = 65;
			tankInfo14.Shots[1].Scale = 150;
			tankInfo14.Shots[1].Splash = new Point(0, 0);
			tankInfo14.Shots[1].Radius = new Point(54, 130);
			tankInfo14.Shots[1].SetAngle(60, 30);
			tankInfo14.Shots[1].SetFocus(60, 30);
			tankInfo14.Shots[2].Delay = 840;
			tankInfo14.Shots[2].Damage = 55;
			tankInfo14.Shots[2].Scale = 125;
			tankInfo14.Shots[2].Splash = new Point(30, 200);
			tankInfo14.Shots[2].Radius = new Point(54, 130);
			tankInfo14.Shots[2].SetAngle(60, 30);
			tankInfo14.Shots[2].SetFocus(60, 30);
			TankInfo tankInfo15 = new TankInfo("Knight")
			{
				IsPrivate = true,
				Armor = ArmorType.Mech,
				Health = 1000,
				DelayBase = 550,
				DelayOffset = 10,
				ShotType = ShotType.Laser,
				ShotStart = new Point(45, 35),
				ShotSpeed = 48,
				ShotWeight = 98
			};
			tankInfo15.Shots[0].Delay = 250;
			tankInfo15.Shots[0].Damage = 156;
			tankInfo15.Shots[0].Scale = 120;
			tankInfo15.Shots[0].Splash = new Point(0, 0);
			tankInfo15.Shots[0].Radius = new Point(48, 110);
			tankInfo15.Shots[0].SetAngle(80, 10);
			tankInfo15.Shots[0].SetFocus(80, 10);
			tankInfo15.Shots[1].Delay = 400;
			tankInfo15.Shots[1].Damage = 87;
			tankInfo15.Shots[1].Scale = 130;
			tankInfo15.Shots[1].Splash = new Point(0, 0);
			tankInfo15.Shots[1].Radius = new Point(40, 120);
			tankInfo15.Shots[1].SetAngle(80, 10);
			tankInfo15.Shots[1].SetFocus(80, 10);
			tankInfo15.Shots[2].Delay = 840;
			tankInfo15.Shots[2].Damage = 97;
			tankInfo15.Shots[2].Scale = 130;
			tankInfo15.Shots[2].Splash = new Point(0, 0);
			tankInfo15.Shots[2].Radius = new Point(40, 120);
			tankInfo15.Shots[2].SetAngle(80, 10);
			tankInfo15.Shots[2].SetFocus(80, 10);
			TankInfo tankInfo16 = new TankInfo("Aduka")
			{
				Armor = ArmorType.Mech,
				Health = 1000,
				DelayBase = 510,
				DelayOffset = 10,
				ShotType = ShotType.Electric,
				ShotStart = new Point(135, 28),
				ShotSpeed = 48,
				ShotWeight = 94
			};
			tankInfo16.Shots[0].Delay = 250;
			tankInfo16.Shots[0].Damage = 124;
			tankInfo16.Shots[0].Scale = 100;
			tankInfo16.Shots[0].Splash = new Point(40, 20);
			tankInfo16.Shots[0].Radius = new Point(64, 120);
			tankInfo16.Shots[0].SetAngle(170, 130);
			tankInfo16.Shots[0].SetFocus(170, 130);
			tankInfo16.Shots[1].Delay = 400;
			tankInfo16.Shots[1].Damage = 200;
			tankInfo16.Shots[1].Scale = 100;
			tankInfo16.Shots[1].Splash = new Point(0, 0);
			tankInfo16.Shots[1].Radius = new Point(120, 100);
			tankInfo16.Shots[1].SetAngle(170, 130);
			tankInfo16.Shots[1].SetFocus(170, 130);
			tankInfo16.Shots[2].Delay = 800;
			tankInfo16.Shots[2].Damage = 600;
			tankInfo16.Shots[2].Scale = 100;
			tankInfo16.Shots[2].Splash = new Point(0, 0);
			tankInfo16.Shots[2].Radius = new Point(160, 100);
			tankInfo16.Shots[2].SetAngle(170, 130);
			tankInfo16.Shots[2].SetFocus(170, 130);
			TankInfo tankInfo17 = new TankInfo("Kalsiddon")
			{
				Armor = ArmorType.Mech,
				Health = 1100,
				DelayBase = 520,
				DelayOffset = 10,
				ShotType = ShotType.Laser,
				ShotStart = new Point(56, 42),
				ShotSpeed = 46,
				ShotWeight = 98
			};
			tankInfo17.Shots[0].Delay = 250;
			tankInfo17.Shots[0].Damage = 135;
			tankInfo17.Shots[0].Scale = 80;
			tankInfo17.Shots[0].FlameScale = 10;
			tankInfo17.Shots[0].Splash = new Point(0, 0);
			tankInfo17.Shots[0].Radius = new Point(55, 134);
			tankInfo17.Shots[0].SetAngle(55, 20);
			tankInfo17.Shots[0].SetFocus(45, 30);
			tankInfo17.Shots[1].Delay = 400;
			tankInfo17.Shots[1].Damage = 225;
			tankInfo17.Shots[1].Scale = 80;
			tankInfo17.Shots[1].FlameScale = 10;
			tankInfo17.Shots[1].Splash = new Point(0, 0);
			tankInfo17.Shots[1].Radius = new Point(42, 124);
			tankInfo17.Shots[1].SetAngle(55, 20);
			tankInfo17.Shots[1].SetFocus(45, 30);
			tankInfo17.Shots[2].Delay = 800;
			tankInfo17.Shots[2].Damage = 337;
			tankInfo17.Shots[2].Scale = 80;
			tankInfo17.Shots[2].FlameScale = 25;
			tankInfo17.Shots[2].Splash = new Point(0, 0);
			tankInfo17.Shots[2].Radius = new Point(48, 126);
			tankInfo17.Shots[2].SetAngle(45, 30);
			tankInfo17.Shots[2].SetFocus(45, 30);
			m_Tanks = new TankInfo[17]
			{
				tankInfo,
				tankInfo2,
				tankInfo3,
				tankInfo4,
				tankInfo5,
				tankInfo6,
				tankInfo7,
				tankInfo8,
				tankInfo9,
				tankInfo10,
				tankInfo11,
				tankInfo12,
				tankInfo13,
				tankInfo14,
				tankInfo15,
				tankInfo16,
				tankInfo17
			};
		}

**Comment by WickedPeanuts** [comment]
Wow, you've got some pretty cool info, where did it come from?
Also, thank you! (: 👍

**Comment by garsia0** [comment]
im working on made gb same as you add me i have tinks good for your project Skype live:garsia  i made a class convert img in managed code to xna textures you can use direct img on the project no need convert to png

**Comment by WickedPeanuts** [comment]
Hello Garsia, sorry for the delayed answer. I dont have skype but you can contact me on discord if you like W.K.#5581 there are several things I still neeed like boomer's formula and a few other things.
